name: CI/CD

on:
  push:
    branches: [main]


jobs:
  build:
    # The type of runner that the job will run on
    name: Upload to S3 and Initializing Code Deploy
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Ref: https://github.com/marketplace/actions/packer-github-actions
    - name: setup node 
      uses: actions/setup-node@v2
      with: 
          node-version: '12.x'
           
    - name: install dependencies
      run:  npm install nodemon
      
    - name: install AWS CLI 
      run:  |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        sudo apt upgrade
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
           aws-region: ${{ secrets.AWS_REGION }}
    - name: Uploading to S3
      run: |
         aws deploy push \
         --application-name csye6225-webapp \
         --description "Changed Version for csye6225-webapp-${{ github.sha }}" \
         --ignore-hidden-files \
         --s3-location s3://${{ secrets.S3_BUCKET }}/csye6225-webapp-${{ github.sha }}.zip \
         --source .
    - name: Creating AWS Deployment
      run: |
          aws deploy create-deployment \
           --application-name csye6225-webapp \
           --deployment-config-name CodeDeployDefault.AllAtOnce \
           --deployment-group-name csye6225-webapp-deployment \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=${{ secrets.S3_BUCKET }},key=csye6225-webapp-${{ github.sha }}.zip,bundleType=zip \